project:
  type: website
  output-dir: docs
  
website:
  title: "Maxwell Heller"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: hobbies.qmd
        text: Hobbies
      

format:
  html:
    theme: vapor
    css: styles.css
    toc: true